name: 'Build domjudge container (PR)'

on:
  push:
  pull_request_target:
    branches:
      - main

env:
  DOMJUDGE_VERSION: M.m.p

jobs:
  pr-domjudge:
    if: ${{ !(github.repository == 'domjudge/domjudge-packaging' &&
              github.ref == 'refs/heads/main') &&
            github.event.action != 'enqueued' &&
            (github.event_name == 'pull_request_target' ||
             github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

