name: 'Build Contributor container (PR)'

on:
  push:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  pr-contributor:
    strategy:
      matrix:
        platform:
          - linux/amd64,
          - linux/arm64/v8
    name: PR Contributor image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container registry (possibly at fork)
        if: (github.ref !== 'refs/heads/main')
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Container registry
        if: github.ref == 'refs/heads/main' && github.repository == 'domjudge/domjudge-packaging'
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        if: ! (github.ref == 'refs/heads/main' && github.repository == 'domjudge/domjudge-packaging')
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Extract metadata (tags, labels) for Docker
        if: github.ref == 'refs/heads/main' && github.repository == 'domjudge/domjudge-packaging'
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: domjudge/domjudge-contributor

      - name: Add extra tag when this is merged
        id: setvars
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "tags=domjudge/domjudge-contributor:${{ env.PLATFORM_PAIR }}" >> $GITHUB_OUTPUT
            echo "name=domjudge/domjudge-contributor" >> $GITHUB_OUTPUT
          else
            echo "tags=${{ steps.meta.outputs.tags }}-${{ env.PLATFORM_PAIR }}" >> $GITHUB_OUTPUT
            echo "name=${{ github.repository }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        id: build
        with:
          context: "./docker-contributor"
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.setvars.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ steps.setvars.output.name }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  # Copied from: https://docs.docker.com/build/ci/github-actions/multi-platform/
  merge:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        if: github.ref == 'refs/heads/main'
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: domjudge/domjudge-contributor

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
