name: 'Build docker containers'

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main
  pull_request_target:
    branches-ignore:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  pr-docker-contributor:
    name: PR Docker contributor image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, arm64v8]
    steps:
      - uses: actions/checkout@v2
      - name: Build container for ${{ matrix.arch }}
        run: |
          exit 0
          if [ "${{ matrix.arch }} = "arm64v8" ]; then
            docker run --privileged --rm tonistiigi/binfmt --install all
          fi
          cd docker-contributor
          docker build --build-arg ARCH=${{ matrix.arch }}/ .
      #- name: Build and push
      #  uses: docker/build-push-action@v5
      #  with:
      #    context: "{{defaultContext}}:docker-contributor"
      #    push: true
      #    tags: domjudge/contributor-pr:latest