name: 'Build docker containers'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  pr-docker-contributor:
    name: PR Docker contributor image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64v8]
    steps:
      - uses: actions/checkout@v2
      - name: Build container for ${{ matrix.arch }}
        run: |
          sudo apt update; sudo apt install docker-buildx-plugin
          cd docker-contributor
          docker build --build-arg ARCH=${{ matrix.arch }}/ .

  pr-docker-contributor-amd64:
    name: PR Docker contributor image (HC: amd64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container for hardcoded amd64
        run: |
          cd docker-contributor
          docker build --build-arg ARCH=amd64/ .

  pr-docker-contributor-arm64:
    name: PR Docker contributor image (HC: arm64v8)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container for hardcoded arm64v8
        run: |
          sudo apt update; sudo apt install docker-buildx-plugin
          cd docker-contributor
          docker build --platform linux/arm64 --build-arg ARCH=arm64v8/ .

