name: 'Build Contributor container (PR)'

on:
  push:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  pr-contributor:
    strategy:
      matrix:
        arch: [amd64, arm64v8]
    name: PR Contributor image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container registry (possibly at fork)
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Container registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Add extra tag when this is merged
        id: setvars
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "tags=domjudge/domjudge-contributor:${{ matrix.arch }}" >> $GITHUB_OUTPUT
          else
            echo "tags=${{ steps.meta.outputs.tags }}-${{ matrix.arch }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: "./docker-contributor" 
          push: true
          tags: ${{ steps.setvars.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
