name: 'Build Contributor container (PR)'

on:
  push:
  pull_request_target:
    branches:
      - main

jobs:
  pr-contributor:
    if: ${{ github.repository != domjudge/domjudge-packaging || github.ref != main }} 
    name: PR Contributor image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64,
          - linux/arm64/v8
    permissions:
      packages: write
      contents: read
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container registry (possibly at fork)
        if: github.ref != 'refs/heads/main'
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        id: build
        with:
          context: "./docker-contributor"
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ github.repository }}/${{ github.ref }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

      - name: TODO list:
        run: |
          # Look at:
          # - https://docs.github.com/en/actions/using-jobs/using-concurrency
          # - https://docs.docker.com/build/ci/github-actions/multi-platform/
          exit 0
