name: 'Build GitLab CI container (PR)'

on:
  push:
  pull_request_target:
    branches:
      - main

jobs:
  pr-gitlab:
    if: ${{ !(github.repository == 'domjudge/domjudge-packaging' &&
              github.ref == 'refs/heads/main') &&
            github.event.action != 'enqueued' &&
            (github.event_name == 'pull_request_target' ||
             github.event.pull_request.head.repo.full_name != github.repository) }}
    name: PR GitLab image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
