name: 'Build Contributor container (PR)'
# For speedup to do this in parallel: https://docs.docker.com/build/ci/github-actions/multi-platform/
# Loosely based on: https://docs.docker.com/build/ci/github-actions/push-multi-registries/

on:
  push:
  pull_request_target:
    branches:
      - main

jobs:
  pr-contributor:
    if: ${{ !(github.repository == 'domjudge/domjudge-packaging' &&
              github.ref == 'refs/heads/main') &&
            github.event.action != 'enqueued' &&
            (github.event_name == 'pull_request_target' ||
             github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: github.event.action
